name: 'Sematext Synthetics CI'
description: 'Runs a Sematext Synthetics monitor on deployment'
inputs:
  api-key:
    description: 'Sematext API Key'
    required: true
  app-id:
    description: 'Sematext App ID'
    required: true
  monitor-id:
    description: 'Sematext Monitor ID'
    required: true
  region:
    description: 'Sematext Region (EU or US)'
    required: true
runs:
  using: composite
  steps:
    - name: Run Sematext Monitor
      shell: bash
      env:
        API_KEY: ${{ inputs.api-key }}
        APP_ID: ${{ inputs.app-id }}
        MONITOR_ID: ${{ inputs.monitor-id }}
        REGION: ${{ inputs.region }}
      run: |
        echo "Running job with the following variables:"
        echo " - APP_ID: ${APP_ID}"
        echo " - MONITOR_ID: ${MONITOR_ID}"
        echo " - REGION: ${REGION}"
        target_url=`cat "$GITHUB_EVENT_PATH" | jq .deployment_status.target_url`
        echo "Running monitor for target URL: $target_url"
        echo " --------------------------------"

        if [ "${REGION}" = "EU" ]; then
          sematext_base_url="https://apps.eu.sematext.com"
        else
          sematext_base_url="https://apps.sematext.com"
        fi

        url="${sematext_base_url}/synthetics-api/api/v3/apps/${APP_ID}/monitors/runs"
        curl -s --request POST \
          --url $url \
            --header 'authorization: apiKey '${API_KEY} \
              --header 'accept: text/plain' \
                --header 'content-type: application/json' \
                  --data '[{"monitorId": '${MONITOR_ID}', "url":'$target_url'}]' > results.txt

        cat results.txt
        if [ $(head -1 results.txt | grep -c 'passed') -ne 1 ]; then exit 1; fi